### ISSUE TITLE
Getting TypeError when installing Ramadan CLI

### ISSUE THREAD

**Issue by mohsinht** [ahmadawais/ramadan-cli#13]
Command:

`npx ramadan-cli lahore`

Error:

```sh
✖ UNHANDLED ERROR
✖ ERROR → TypeError
ℹ REASON → input.toLowerCase(...).replaceAll is not a function
ℹ ERROR STACK ↓ 
 TypeError: input.toLowerCase(...).replaceAll is not a function
    at /Users/mohsinhayat/.npm/_npx/19728/lib/node_modules/ramadan-cli/index.js:18:35
    at Object.<anonymous> (/Users/mohsinhayat/.npm/_npx/19728/lib/node_modules/ramadan-cli/index.js:23:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at /Users/mohsinhayat/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

Node version: v14.17.6
MacOS: 12.3
Npm version: 6.14.15

**Comment by ahmadawais** [comment]
That's because I was using and always encourage using current Node version, but I see the LTS doesn't support `.replaceAll()` so I'll roll back. This is fixed now.
