### ISSUE TITLE
having problem in Npx command  . whenever i am entering Node index.js it is working otherwise lol

### ISSUE THREAD

**Issue by madilraza** [ahmadawais/ramadan-cli#8]
C:\Users\marsec developer\ramadan-cli>npx ramadan-cli
Error: EPERM: operation not permitted, mkdir 'C:\Users\marsec'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\utils\error-handler.js:213:18)
    at C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\npm.js:215:22)
    at C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\npm.js:253:24
    at C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\config\core.js:178:20)
    at C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\node_modules\mkdirp\index.js:47:53
C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\utils\error-handler.js:213
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Users\marsec developer\AppData\Roaming\npm\node_modules\npx\node_modules\npm\lib\utils\error-handler.js:213:18)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)
Install for [ 'ramadan-cli@latest' ] failed with code 7

**Comment by ahmadawais** [comment]
You must be using a super old version of Node.js. Anything below v12 is not what I support nor is it officially supported.

**Comment by ahmadawais** [comment]
Stop creating multiple comments to send out multiple emails. That's not nice. 

You should also use Google first to see if you can solve your problems. 

Your error when I searched it on Google. The first link had a solution.

https://github.com/zkat/npx/issues/100#issuecomment-344293820
